export const CART_AMOUNT_INCREMENT = 'CART_AMOUNT_INCREMENT'
export const CART_AMOUNT_DECREMENT = 'CART_AMOUNT_DECREMENT'
// export default {
//   CART_AMOUNT_INCREMENT:'CART_AMOUNT_INCREMENT',
//   CART_AMOUNT_DECREMENT:'CART_AMOUNT_DECREMENT'
// }